// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzqssxccbcozzemollyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6cXNzeGNjYmNvenplbW9sbHl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MTgwMzQsImV4cCI6MjA1OTA5NDAzNH0.AmZK142CD1--8zLRYgZ0e7Q0Ii7lIaJau34pn9Lf_rI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

console.log("Initializing Supabase client with URL:", SUPABASE_URL);
console.log("Key starts with:", SUPABASE_PUBLISHABLE_KEY.substring(0, 10) + "...");

// Create a safer client initialization that works in both browser and server environments
const createSafeClient = () => {
  try {
    // More robust environment detection
    const isBrowser = typeof window !== 'undefined' && typeof window.document !== 'undefined';
    const isNode = typeof process !== 'undefined' && process.versions != null && process.versions.node != null;

    console.log('Environment detection:', { isBrowser, isNode });

    // Basic client configuration
    const config = {
      auth: {
        persistSession: false,
        autoRefreshToken: false,
      }
    };

    // Create client with minimal configuration
    const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, config);
    
    console.log('Supabase client created successfully');
    return client;
  } catch (error) {
    console.error("Error during Supabase client creation:", error);
    // Fallback to most basic client configuration
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
  }
};

// Initialize the client
const supabaseClient = createSafeClient();

// Log successful initialization but don't test connection
console.log("Supabase client initialized");

// Export the client
export const supabase = supabaseClient;
